import { getChatGPTUser } from "../../chatgpt-auth";
import { getSupabaseServerClient } from "../../../lib/supabase/server";
import { sendExternalNotification, sendToOfficialShelter } from "../../../lib/integrations";
import { clean } from "../_helpers";

type Row = Record<string, unknown>;
const map = (row: Row) => ({ ...row, memberId: row.member_id, animalId: row.animal_id, guardianId: row.guardian_id, shelterPublicId: row.shelter_public_id, createdAt: row.created_at, updatedAt: row.updated_at });
const operator = (role: unknown) => role === "admin" || role === "shelter";

async function context() {
  const user = await getChatGPTUser(); if (!user) return null;
  const client = getSupabaseServerClient(), { data: member } = await client.from("members").select("*").eq("id", user.userId).maybeSingle();
  return member ? { user, member, client } : null;
}
async function audit(client: ReturnType<typeof getSupabaseServerClient>, actorId: string, action: string, targetType: string, targetId: string, before?: unknown, after?: unknown) {
  await client.from("admin_audit_logs").insert({ actor_id: actorId, action, target_type: targetType, target_id: targetId, before_json: JSON.stringify(before || {}), after_json: JSON.stringify(after || {}) });
}

export async function GET() {
  const auth = await context(); if (!auth) return Response.json({ error: "본인 확인이 필요합니다." }, { status: 401 });
  if (!operator(auth.member.role)) return Response.json({ error: "인증된 보호소 또는 운영자만 이용할 수 있습니다." }, { status: 403 });
  const admin = auth.member.role === "admin", c = auth.client;
  const [applications, registrations, verifications, reports, audits, certifications, appeals, fundraisers, returns] = await Promise.all([
    c.from("applications").select("*").order("readiness_score", { ascending: false }).order("created_at", { ascending: false }).limit(50),
    admin ? c.from("direct_animals").select("*").order("created_at", { ascending: false }).limit(50) : c.from("direct_animals").select("*").eq("member_id", auth.user.userId).order("created_at", { ascending: false }).limit(50),
    admin ? c.from("verification_requests").select("*").order("created_at", { ascending: false }).limit(30) : Promise.resolve({ data: [] }),
    admin ? c.from("reports").select("*").order("created_at", { ascending: false }).limit(50) : Promise.resolve({ data: [] }),
    admin ? c.from("admin_audit_logs").select("*").order("created_at", { ascending: false }).limit(50) : Promise.resolve({ data: [] }),
    admin ? c.from("adoption_certifications").select("*").order("created_at", { ascending: false }).limit(30) : Promise.resolve({ data: [] }),
    admin ? c.from("sanction_appeals").select("*").order("created_at", { ascending: false }).limit(30) : Promise.resolve({ data: [] }),
    admin ? c.from("fundraisers").select("*").order("created_at", { ascending: false }).limit(50) : Promise.resolve({ data: [] }),
    c.from("return_requests").select("*").order("created_at", { ascending: false }).limit(50),
  ]);
  const applicationRows = (applications.data || []).filter(row => admin || row.guardian_id === auth.user.userId), registrationRows = registrations.data || [], returnRows = (returns.data || []).filter(row => admin || applicationRows.some(application => application.id === row.application_id));
  return Response.json({ summary: { applications: applicationRows.length, reviews: registrationRows.filter(row => row.status === "review").length, reports: reports.data?.length || 0, returns: returnRows.filter(row => row.status !== "resolved").length }, applications: applicationRows.map(map), registrations: registrationRows.map(map), verifications: (verifications.data || []).map(map), reports: (reports.data || []).map(map), returns: returnRows.map(map), audits: (audits.data || []).map(map), certifications: (certifications.data || []).map(map), appeals: (appeals.data || []).map(map), fundraisers: (fundraisers.data || []).map(map) });
}

export async function POST(request: Request) {
  const auth = await context(); if (!auth) return Response.json({ error: "본인 확인이 필요합니다." }, { status: 401 });
  if (!operator(auth.member.role)) return Response.json({ error: "운영자 권한이 필요합니다." }, { status: 403 });
  const c = auth.client, data = await request.json() as Record<string, unknown>, action = clean(data.action, 40), id = Number(data.id), note = clean(data.note, 500), admin = auth.member.role === "admin";
  if (action === "application-status") {
    const status = clean(data.status, 30), allowed = ["review", "consulting", "approved", "rejected", "handover", "completed", "return_support"];
    if (!allowed.includes(status)) return Response.json({ error: "상태를 확인해 주세요." }, { status: 400 });
    const { data: current } = await c.from("applications").select("*").eq("id", id).maybeSingle(); if (!current || (!admin && current.guardian_id !== auth.user.userId)) return Response.json({ error: "담당 신청만 처리할 수 있습니다." }, { status: 403 });
    const { data: row } = await c.from("applications").update({ status }).eq("id", id).select("*").single(); await c.from("application_events").insert({ application_id: id, actor_id: auth.user.userId, event_type: `status:${status}`, note }); await c.from("notifications").insert({ member_id: current.member_id, type: "application_status", title: "입양 신청 상태가 변경됐어요", body: `신청 #${id}: ${status}`, href: `/applications/${id}` }); await sendExternalNotification({ memberId: current.member_id, title: "입양 신청 상태 변경", body: status });
    const shelterTransfer = status === "review" ? await sendToOfficialShelter({ applicationId: id, animalId: current.animal_id }) : null; return Response.json({ row: row ? map(row) : null, shelterTransfer });
  }
  if (action === "guardian-message") {
    const { data: current } = await c.from("applications").select("*").eq("id", id).maybeSingle(), body = clean(data.body, 1000); if (!current || (!admin && current.guardian_id !== auth.user.userId)) return Response.json({ error: "담당 신청만 상담할 수 있습니다." }, { status: 403 }); if (body.length < 2) return Response.json({ error: "메시지를 입력해 주세요." }, { status: 400 }); const { data: message } = await c.from("application_messages").insert({ application_id: id, sender_id: auth.user.userId, body }).select("*").single(); await c.from("notifications").insert({ member_id: current.member_id, type: "application_message", title: "보호처에서 상담 메시지가 왔어요", body: body.slice(0, 100), href: `/applications/${id}` }); return Response.json({ message }, { status: 201 });
  }
  if (action === "return-status") {
    const status = clean(data.status, 20); if (!["connected", "resolved"].includes(status)) return Response.json({ error: "상태를 확인해 주세요." }, { status: 400 }); const { data: requestRow } = await c.from("return_requests").select("*").eq("id", id).maybeSingle(); const { data: application } = requestRow ? await c.from("applications").select("*").eq("id", requestRow.application_id).maybeSingle() : { data: null }; if (!requestRow || !application || (!admin && application.guardian_id !== auth.user.userId)) return Response.json({ error: "담당 요청만 처리할 수 있습니다." }, { status: 403 }); const { data: row } = await c.from("return_requests").update({ status }).eq("id", id).select("*").single(); await c.from("notifications").insert({ member_id: requestRow.member_id, type: "return_support", title: "돌봄 위기 도움 상태가 바뀌었어요", body: status === "connected" ? "보호처가 상담·임시돌봄 연결을 확인하고 있어요." : "도움 요청이 해결됨으로 기록됐어요.", href: `/applications/${requestRow.application_id}` }); return Response.json({ row: row ? map(row) : null });
  }
  if (action === "registration-status") { if (!admin) return Response.json({ error: "직접 등록 공개 심사는 운영자만 할 수 있습니다." }, { status: 403 }); const status = clean(data.status, 20); if (!["published", "closed"].includes(status)) return Response.json({ error: "상태를 확인해 주세요." }, { status: 400 }); const { data: row } = await c.from("direct_animals").update({ status, updated_at: new Date().toISOString() }).eq("id", id).select("*").maybeSingle(); return Response.json({ row: row ? map(row) : null }); }
  if (action === "moderate") { if (!admin) return Response.json({ error: "안전 조치는 운영자만 할 수 있습니다." }, { status: 403 }); await c.from("moderation_actions").insert({ actor_id: auth.user.userId, target_type: clean(data.targetType, 30), target_id: clean(data.targetId, 40), action: clean(data.moderationAction, 40), reason: note || "운영 정책에 따른 조치" }); return Response.json({ ok: true }); }
  if (action === "verification-status") { if (!admin) return Response.json({ error: "역할 인증 심사는 운영자만 할 수 있습니다." }, { status: 403 }); const status = clean(data.status, 20); if (!["verified", "rejected"].includes(status)) return Response.json({ error: "심사 상태를 확인해 주세요." }, { status: 400 }); const { data: before } = await c.from("verification_requests").select("*").eq("id", id).maybeSingle(); const { data: row } = await c.from("verification_requests").update({ status, reviewed_by: auth.user.userId }).eq("id", id).select("*").maybeSingle(); if (row && status === "verified") await c.from("members").update({ role: row.requested_role, verified: true }).eq("id", row.member_id); await audit(c, auth.user.userId, `verification:${status}`, "verification", String(id), before, row); return Response.json({ row: row ? map(row) : null }); }
  if (action === "post-visibility") { if (!admin) return Response.json({ error: "게시물 안전 조치는 운영자만 할 수 있습니다." }, { status: 403 }); const hidden = data.hidden === true; const { data: before } = await c.from("posts").select("*").eq("id", id).maybeSingle(); const { data: row } = await c.from("posts").update({ hidden }).eq("id", id).select("*").maybeSingle(); await audit(c, auth.user.userId, hidden ? "post:hidden" : "post:restored", "post", String(id), before, row); return Response.json({ row: row ? map(row) : null }); }
  if (action === "adoption-certification-status") { if (!admin) return Response.json({ error: "입양 인증 심사는 운영자만 할 수 있습니다." }, { status: 403 }); const status = clean(data.status, 20); if (!["verified", "rejected"].includes(status)) return Response.json({ error: "상태를 확인해 주세요." }, { status: 400 }); const { data: row } = await c.from("adoption_certifications").update({ status, reviewed_by: auth.user.userId }).eq("id", id).select("*").maybeSingle(); if (!row) return Response.json({ error: "인증 요청을 찾을 수 없습니다." }, { status: 404 }); await audit(c, auth.user.userId, `adoption-certification:${status}`, "adoption-certification", String(id), undefined, row); await c.from("notifications").insert({ member_id: row.member_id, type: "adoption_certification", title: "입양 인증 검토 결과", body: status === "verified" ? "입양 인증이 완료되어 입양 일기를 작성할 수 있어요." : "입양 인증 자료를 다시 확인해 주세요.", href: "/adoption-verification" }); return Response.json({ row: map(row) }); }
  if (action === "appeal-status") { if (!admin) return Response.json({ error: "이의제기 심사는 운영자만 할 수 있습니다." }, { status: 403 }); const status = clean(data.status, 20); const { data: appeal } = await c.from("sanction_appeals").select("*").eq("id", id).maybeSingle(); if (!appeal || !["accepted", "rejected"].includes(status)) return Response.json({ error: "이의제기와 상태를 확인해 주세요." }, { status: 400 }); const { data: row } = await c.from("sanction_appeals").update({ status, reviewed_by: auth.user.userId }).eq("id", id).select("*").single(); await c.from("account_sanctions").update({ status: status === "accepted" ? "lifted" : "confirmed" }).eq("id", appeal.sanction_id); if (status === "accepted") await c.from("members").update({ sanctioned: false }).eq("id", appeal.member_id); await audit(c, auth.user.userId, `appeal:${status}`, "sanction-appeal", String(id), undefined, row); return Response.json({ row: row ? map(row) : null }); }
  if (action === "account-sanction-target") {
    if (!admin) return Response.json({ error: "계정 제재 확정은 운영자만 할 수 있습니다." }, { status: 403 });
    const { data: report } = await c.from("reports").select("*").eq("id", id).maybeSingle(); if (!report) return Response.json({ error: "신고를 찾을 수 없습니다." }, { status: 404 });
    let memberId = "";
    if (report.target_type === "post") { const { data: target } = await c.from("posts").select("member_id").eq("id", Number(report.target_id)).maybeSingle(); memberId = String(target?.member_id || ""); }
    else if (report.target_type === "animal" && String(report.target_id).startsWith("direct-")) { const { data: target } = await c.from("direct_animals").select("member_id").eq("id", Number(String(report.target_id).slice(7))).maybeSingle(); memberId = String(target?.member_id || ""); }
    if (!memberId) return Response.json({ error: "신고 대상 계정을 확인할 수 없어 제재하지 않았습니다." }, { status: 422 });
    const { data: target } = await c.from("members").select("email").eq("id", memberId).maybeSingle(); if (!target) return Response.json({ error: "계정을 찾을 수 없습니다." }, { status: 404 });
    const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(String(target.email).trim().toLowerCase())), fingerprintHash = Array.from(new Uint8Array(digest), v => v.toString(16).padStart(2, "0")).join(""), reason = note || "운영자 신고 검토 후 확정";
    await c.from("members").update({ sanctioned: true }).eq("id", memberId); const { data: row } = await c.from("account_sanctions").insert({ member_id: memberId, actor_id: auth.user.userId, reason, status: "confirmed", fingerprint_hash: fingerprintHash }).select("*").single(); await audit(c, auth.user.userId, "account:sanctioned", "member", memberId, undefined, { reason, reportId: id }); return Response.json({ row });
  }
  if (action === "fundraiser-status") { if (!admin) return Response.json({ error: "모금 공개 심사는 운영자만 할 수 있습니다." }, { status: 403 }); const status = clean(data.status, 20); if (!["open", "rejected", "settled"].includes(status)) return Response.json({ error: "모금 상태를 확인해 주세요." }, { status: 400 }); const { data: before } = await c.from("fundraisers").select("*").eq("id", id).maybeSingle(); if (!before) return Response.json({ error: "모금 신청을 찾을 수 없습니다." }, { status: 404 }); const { data: row } = await c.from("fundraisers").update({ status }).eq("id", id).select("*").single(); await audit(c, auth.user.userId, `fundraiser:${status}`, "fundraiser", String(id), before, row); return Response.json({ row: row ? map(row) : null }); }
  if (action === "guardian-confirm-handover") { const { data: application } = await c.from("applications").select("*").eq("id", id).maybeSingle(); if (!application || (!admin && application.guardian_id !== auth.user.userId)) return Response.json({ error: "담당 신청만 인계 확인할 수 있습니다." }, { status: 403 }); const { data: reservation } = await c.from("handover_reservations").select("*").eq("application_id", id).maybeSingle(); if (!reservation) return Response.json({ error: "인계 예약을 찾을 수 없습니다." }, { status: 404 }); await c.from("handover_reservations").update({ guardian_confirmed: true, status: reservation.adopter_confirmed ? "completed" : "confirmed" }).eq("application_id", id); if (reservation.adopter_confirmed) await c.from("applications").update({ status: "completed" }).eq("id", id); await audit(c, auth.user.userId, "handover:guardian-confirmed", "application", String(id), undefined, { guardianConfirmed: true }); return Response.json({ ok: true }); }
  return Response.json({ error: "지원하지 않는 작업입니다." }, { status: 400 });
}
