/* eslint-disable react-hooks/set-state-in-effect -- open-state controls a remote filter options request */
"use client";

import { useEffect, useState } from "react";
import { IconXmarkLine } from "@karrotmarket/react-monochrome-icon";
import { ActionButton } from "seed-design/ui/action-button";
import { LoadingIndicator } from "./LoadingIndicator";
import type { AnimalFeedFilters } from "./useAnimalFeed";

type Options = { species: string[]; breeds: { key: string; label: string; species: string }[]; sex: string[]; colors: string[]; ages: string[]; weights: string[]; states: string[]; regions: string[] };
type Props = { activeCount: number; setFilter: <K extends keyof AnimalFeedFilters>(key: K, value: AnimalFeedFilters[K]) => void; resetFilters: () => void };

function Group({ title, values, selected, onToggle }: { title: string; values: string[]; selected: string[]; onToggle: (value: string) => void }) {
  return <section className="ff-all-filter-group"><h2>{title}</h2><div className="ff-all-filter-options">{values.map(value => <label key={value}><input type="checkbox" checked={selected.includes(value)} onChange={() => onToggle(value)} /><span>{value}</span></label>)}</div></section>;
}

export function AllAnimalFilters({ activeCount, setFilter, resetFilters }: Props) {
  const [open, setOpen] = useState(false), [loading, setLoading] = useState(false), [error, setError] = useState(""), [options, setOptions] = useState<Options | null>(null);
  const [species, setSpecies] = useState<string[]>([]), [breeds, setBreeds] = useState<string[]>([]), [sex, setSex] = useState<string[]>([]), [colors, setColors] = useState<string[]>([]), [ages, setAges] = useState<string[]>([]), [weights, setWeights] = useState<string[]>([]), [states, setStates] = useState<string[]>([]), [regions, setRegions] = useState<string[]>([]);
  const toggle = (setter: React.Dispatch<React.SetStateAction<string[]>>) => (value: string) => setter(current => current.includes(value) ? current.filter(item => item !== value) : [...current, value]);
  useEffect(() => { if (!open || options) return; setLoading(true); fetch("/api/animal-filter-options").then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error || "공공 API 필터를 불러오지 못했어요."); setOptions(body); }).catch(value => setError(value instanceof Error ? value.message : "공공 API 필터를 불러오지 못했어요.")).finally(() => setLoading(false)); }, [open, options]);
  const apply = () => { const selectedSpecies = species.length === 1 && /고양이/.test(species[0]) ? "cat" : species.length === 1 && /개|강아지/.test(species[0]) ? "dog" : "all"; const selectedSex = sex.length === 1 && sex[0] === "암컷" ? "female" : sex.length === 1 && sex[0] === "수컷" ? "male" : "all"; setFilter("species", selectedSpecies); setFilter("sex", selectedSex); setFilter("color", colors.length === 1 ? colors[0] : "all"); setFilter("breedKeys", breeds.slice(0, 10)); setOpen(false); };
  return <><button type="button" className="ff-all-filter-trigger" onClick={() => setOpen(true)} aria-label="전체 필터 열기"><span aria-hidden>☷</span><strong>필터</strong>{activeCount > 0 && <b>{activeCount}</b>}</button>{open && <div className="ff-all-filter-overlay" role="dialog" aria-modal="true" aria-label="공공 API 전체 필터"><header className="ff-all-filter-header"><div><span className="ff-kicker">공공 API 원문 기준</span><h1>어떤 친구를 찾고 있나요?</h1></div><button type="button" onClick={() => setOpen(false)} aria-label="필터 닫기"><IconXmarkLine aria-hidden /></button></header><div className="ff-all-filter-content">{loading && <div className="ff-all-filter-loading"><LoadingIndicator label="공공 API 필터를 불러오는 중" /></div>}{error && <p className="ff-all-filter-error">{error}</p>}{options && <><Group title="종류" values={options.species} selected={species} onToggle={toggle(setSpecies)} /><section className="ff-all-filter-group"><h2>품종</h2><div className="ff-all-filter-options">{options.breeds.map(item => <label key={item.key}><input type="checkbox" checked={breeds.includes(item.key)} onChange={() => toggle(setBreeds)(item.key)} /><span>{item.label}<small>{item.species}</small></span></label>)}</div></section><Group title="성별" values={options.sex} selected={sex} onToggle={toggle(setSex)} /><Group title="털색 원문" values={options.colors} selected={colors} onToggle={toggle(setColors)} /><Group title="나이 원문" values={options.ages} selected={ages} onToggle={toggle(setAges)} /><Group title="체중 원문" values={options.weights} selected={weights} onToggle={toggle(setWeights)} /><Group title="보호 상태 원문" values={options.states} selected={states} onToggle={toggle(setStates)} /><Group title="발견 지역 원문" values={options.regions} selected={regions} onToggle={toggle(setRegions)} /></>}</div><footer className="ff-all-filter-footer"><button type="button" onClick={() => { setSpecies([]); setBreeds([]); setSex([]); setColors([]); setAges([]); setWeights([]); setStates([]); setRegions([]); resetFilters(); }}>전체 초기화</button><ActionButton onClick={apply}>선택 조건 적용</ActionButton></footer></div>}</>;
}
