"use client";
import { useEffect, useState } from "react";
import { ActionButton } from "seed-design/ui/action-button";
import { Callout } from "seed-design/ui/callout";
import { Checkbox } from "seed-design/ui/checkbox";
import { TextField } from "seed-design/ui/text-field";
import { RadioGroup, RadioGroupItem } from "seed-design/ui/radio-group";
import { useAppFeedback } from "./AppFeedback";

type Data = { application: { id:number; animalId:string; status:string; readinessScore:number; household:string; carePlan:string; absencePlan:string; emergencyPlan:string; createdAt:string }; agreement?: { signedName:string; agreedAt:string }; handover?: { method:string; scheduledAt:string; region:string; adopterConfirmed:boolean; guardianConfirmed:boolean; checklistJson:string }; returnRequest?:{urgency:string;status:string}; messages: { id:number; body:string; createdAt:string }[] };
const steps = ["신청 접수", "내용 검토", "상담", "승인", "약정·인계"];
const stage: Record<string, number> = { submitted: 0, review: 1, consulting: 2, approved: 3, rejected: -1, handover: 4, completed: 4, return_support: 4, withdrawn: -1 };

export function ApplicationProgress({ id }: { id:number }) {
  const feedback = useAppFeedback();
  const [data, setData] = useState<Data|null>(null), [error, setError] = useState("");
  const [message, setMessage] = useState(""), [signedName, setSignedName] = useState(""), [accepted, setAccepted] = useState(false);
  const [method, setMethod] = useState("visit"), [scheduledAt, setScheduledAt] = useState(""), [region, setRegion] = useState("");
  const [showCrisis,setShowCrisis]=useState(false),[urgency,setUrgency]=useState("consult"),[crisisReason,setCrisisReason]=useState(""),[safeUntil,setSafeUntil]=useState("");
  const load = () => fetch(`/api/applications/${id}`).then(r => r.json()).then(v => v.error ? setError(v.error) : setData(v)).catch(() => setError("신청 정보를 불러오지 못했어요."));
  useEffect(load, [id]);
  const post = async (payload: Record<string, unknown>) => { setError(""); const response = await fetch(`/api/applications/${id}`, { method:"POST", headers:{"content-type":"application/json"}, body:JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) { const message=body.error || "처리하지 못했어요."; setError(message); feedback.error(message); return; } const labels:Record<string,string>={message:"메시지를 보냈어요",agreement:"전자 약정에 서명했어요",handover:"인계 일정을 제안했어요","confirm-handover":"인계받음 확인을 저장했어요","return-support":"비공개 도움 요청을 접수했어요"}; feedback.success(labels[String(payload.action)]||"변경 내용을 저장했어요"); await load(); };
  if (!data) return <div className="ff-result">{error || "신청 정보를 불러오는 중이에요…"}</div>;
  const current = stage[data.application.status] ?? 0;
  return <>
    {data.application.status === "withdrawn" || data.application.status === "rejected" ? <Callout tone="warning" title="종료된 신청입니다" description="새로운 만남을 찾을 때에는 준비 내용을 다시 확인해 주세요."/> : <ol className="ff-progress-steps">{steps.map((label,index)=><li className={index <= current ? "is-done" : ""} key={label}><span>{index + 1}</span><strong>{label}</strong></li>)}</ol>}
    {error && <Callout tone="critical" description={error}/>} 
    <section className="ff-section ff-result"><h2 className="ff-section-title">신청한 돌봄 계획</h2><dl className="ff-detail-list"><div><dt>함께 사는 환경</dt><dd>{data.application.household}</dd></div><div><dt>일상 돌봄</dt><dd>{data.application.carePlan}</dd></div><div><dt>부재 시 계획</dt><dd>{data.application.absencePlan}</dd></div><div><dt>응급 계획</dt><dd>{data.application.emergencyPlan}</dd></div></dl></section>
    <section className="ff-section"><h2 className="ff-section-title">보호처와 안전 메시지</h2><p className="ff-description">전화번호나 정확한 주소 대신 이 공간에서 먼저 상담하세요. 운영 기록은 분쟁과 안전 확인에 활용됩니다.</p><div className="ff-message-list">{data.messages.map(item=><div key={item.id}><p>{item.body}</p><small>{new Date(item.createdAt).toLocaleString("ko-KR")}</small></div>)}</div><TextField label="문의 또는 상담 내용" value={message} onChange={e=>setMessage(e.target.value)} /><ActionButton style={{marginTop:8}} onClick={()=>post({action:"message",body:message}).then(()=>setMessage(""))}>메시지 보내기</ActionButton></section>
    {data.application.status === "approved" && !data.agreement && <section className="ff-section ff-result"><h2 className="ff-section-title">표준 전자 입양 약정</h2><p className="ff-description">정보를 사실대로 확인하고, 평생 돌봄·재판매 금지·파양 전 보호처 상담·학대 의심 신고에 동의합니다. 이 약정은 사적 처벌 조항을 두지 않습니다.</p><TextField label="서명 이름" value={signedName} onChange={e=>setSignedName(e.target.value)}/><Checkbox checked={accepted} onCheckedChange={setAccepted} label="다섯 가지 필수 약정 내용을 확인하고 동의합니다"/><ActionButton onClick={()=>post({action:"agreement",signedName,allAccepted:accepted})}>서명 완료</ActionButton></section>}
    {data.agreement && !data.handover && <section className="ff-section ff-result"><h2 className="ff-section-title">인계 예약</h2><RadioGroup label="안전한 이동 방법" value={method} onValueChange={setMethod}><RadioGroupItem value="visit" label="직접 방문"/><RadioGroupItem value="volunteer" label="검증 봉사자 동행"/><RadioGroupItem value="transport" label="전문 운송"/></RadioGroup><TextField label="희망 일시" type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)}/><TextField label="만남 지역(시·군·구까지만)" value={region} onChange={e=>setRegion(e.target.value)}/><ActionButton onClick={()=>post({action:"handover",method,scheduledAt,region})}>인계 제안 보내기</ActionButton></section>}
    {data.handover && <section className="ff-section ff-result"><h2 className="ff-section-title">인계 안전 체크</h2><p><strong>{data.handover.scheduledAt}</strong> · {data.handover.region} · {{visit:"직접 방문",volunteer:"봉사자 동행",transport:"전문 운송"}[data.handover.method as "visit"]}</p><ActionButton asChild size="small" variant="neutralWeak"><a href={`https://map.kakao.com/link/search/${encodeURIComponent(data.handover.region)}`} target="_blank" rel="noreferrer">대략 위치 지도 보기</a></ActionButton><p className="ff-meta">공개 지도에는 시·군·구까지만 전달하며 정확한 만남 장소는 내부 상담에서 확인해요.</p><ul className="ff-check-list">{JSON.parse(data.handover.checklistJson).map((item:string)=><li key={item}>{item}</li>)}</ul><Callout tone={data.handover.adopterConfirmed && data.handover.guardianConfirmed ? "positive" : "informative"} description={data.handover.adopterConfirmed && data.handover.guardianConfirmed ? "양측 인계 확인이 완료됐어요." : "입양자와 보호자가 모두 확인해야 인계가 완료됩니다."}/>{!data.handover.adopterConfirmed && <ActionButton onClick={()=>post({action:"confirm-handover"})}>인계받음 확인</ActionButton>}</section>}
    <section className="ff-section"><h2 className="ff-section-title">돌봄이 어려워졌나요?</h2><p className="ff-description">숨기거나 다시 유기하지 마세요. 원 보호처 상담, 단기 돌봄, 긴급 임시보호 가능성을 함께 찾습니다.</p>{data.returnRequest?<Callout tone="positive" title="도움 요청을 확인하고 있어요" description={`현재 상태: ${data.returnRequest.status}`}/>:showCrisis?<div className="ff-form"><div className="ff-field"><label htmlFor="urgency">도움이 필요한 시점</label><select id="urgency" className="ff-native-select" value={urgency} onChange={e=>setUrgency(e.target.value)}><option value="consult">상담부터 필요해요</option><option value="soon">며칠 안에 도움이 필요해요</option><option value="emergency">오늘 안전한 장소가 필요해요</option></select></div><TextField label="현재 상황" value={crisisReason} onChange={e=>setCrisisReason(e.target.value)}/><TextField label="현재 돌봄 가능한 시점" value={safeUntil} onChange={e=>setSafeUntil(e.target.value)} placeholder="예: 이번 주 금요일까지"/>{urgency==="emergency"&&<Callout tone="critical" description="동물 또는 사람에게 즉각적인 위험이 있으면 112나 관할 지자체에 먼저 연락하세요."/>}<ActionButton onClick={()=>post({action:"return-support",urgency,reason:crisisReason,safeUntil})}>비공개 도움 요청</ActionButton></div>:<ActionButton variant="neutralWeak" onClick={()=>setShowCrisis(true)}>돌봄 위기 도움 요청</ActionButton>}</section>
  </>;
}
