"use client";
import { useState } from "react";
import { ActionButton } from "seed-design/ui/action-button";
import { Callout } from "seed-design/ui/callout";
import { Checkbox } from "seed-design/ui/checkbox";
import { SegmentedControl, SegmentedControlItem } from "seed-design/ui/segmented-control";
import { TextField, TextFieldInput } from "seed-design/ui/text-field";

export function AuthForm({ returnTo = "/mypage", oauthStatus = "", provider = "" }: { returnTo?: string; oauthStatus?: string; provider?: string }) {
  const [mode, setMode] = useState("login"), [terms, setTerms] = useState(false), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); try { const form = new FormData(event.currentTarget); const response = await fetch(`/api/auth/${mode}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email: form.get("email"), password: form.get("password"), displayName: form.get("displayName"), termsAccepted: terms, returnTo }) }); const body = await response.json().catch(() => ({})) as { error?: string; returnTo?: string }; if (response.ok) location.href = body.returnTo || returnTo; else setError(body.error || "계정을 확인하지 못했어요."); } catch { setError("네트워크 연결을 확인하고 다시 시도해 주세요."); } finally { setBusy(false); } }
  return <div className="ff-auth-card"><SegmentedControl aria-label="로그인 방식" value={mode} onValueChange={value => setMode(String(value))}><SegmentedControlItem value="login">로그인</SegmentedControlItem><SegmentedControlItem value="register">이메일 가입</SegmentedControlItem></SegmentedControl>{oauthStatus === "unconfigured" && <Callout tone="warning" title={`${providerLabel(provider)} 로그인 준비 중`} description="서비스 운영자가 해당 소셜 앱 키를 등록하면 바로 사용할 수 있어요. 지금은 이메일로 가입할 수 있습니다."/>}{oauthStatus && oauthStatus !== "unconfigured" && <Callout tone="critical" description="소셜 로그인을 완료하지 못했어요. 다시 시도해 주세요."/>}<form className="ff-form" onSubmit={submit}>{mode === "register" && <TextField label="이름"><TextFieldInput name="displayName" autoComplete="name" required/></TextField>}<TextField label="이메일"><TextFieldInput name="email" type="email" autoComplete="email" required/></TextField><TextField label="비밀번호" description={mode === "register" ? "10자 이상으로 설정해 주세요." : undefined}><TextFieldInput name="password" type="password" autoComplete={mode === "register" ? "new-password" : "current-password"} minLength={10} required/></TextField>{mode === "register" && <Checkbox label="이용약관과 개인정보 처리방침에 동의합니다" checked={terms} onCheckedChange={setTerms}/>} {error && <Callout tone="critical" description={error}/>}<ActionButton size="large" disabled={busy || (mode === "register" && !terms)}>{busy ? "확인 중" : mode === "register" ? "계정 만들기" : "로그인"}</ActionButton></form><div className="ff-auth-divider"><span>또는</span></div><div className="ff-social-login"><a href={`/api/auth/oauth/kakao?return_to=${encodeURIComponent(returnTo)}`}>카카오로 계속</a><a href={`/api/auth/oauth/naver?return_to=${encodeURIComponent(returnTo)}`}>네이버로 계속</a><a href={`/api/auth/oauth/google?return_to=${encodeURIComponent(returnTo)}`}>Google로 계속</a></div><a className="ff-meta" href={`/api/auth/oauth/kakao?test=1&return_to=${encodeURIComponent(returnTo)}`}>테스트 카카오 로그인</a><p className="ff-meta">개발용 테스트 계정으로 로그인합니다. 가입하면 <a href="/terms">이용약관</a>과 <a href="/privacy">개인정보 처리방침</a>을 확인하고 동의한 것으로 기록됩니다.</p></div>;
}
function providerLabel(value: string) { return value === "kakao" ? "카카오" : value === "naver" ? "네이버" : "Google"; }
