"use client";
import {useEffect,useState} from "react";
import {ActionButton} from "seed-design/ui/action-button";
import {Callout} from "seed-design/ui/callout";
import {Checkbox,CheckboxGroup} from "seed-design/ui/checkbox";
import {TextField,TextFieldInput,TextFieldTextarea} from "seed-design/ui/text-field";
import {sanitizeImageFile} from "../../lib/client-image";
const questions=[{q:"동물 자체의 가격이나 개인 수익 목적의 책임비를 요구할 수 있나요?",a:false},{q:"공개 글에 정확한 구조 위치와 개인 연락처를 적어야 하나요?",a:false},{q:"알고 있는 질병·치료·구조 경위는 사실대로 공개해야 하나요?",a:true},{q:"입양 신청자를 빨리 온 순서로만 결정해야 하나요?",a:false},{q:"돌봄이 어려워지면 숨기지 말고 도움을 요청해야 하나요?",a:true}];
const terms=["동물 가격·개인 수익 목적의 책임비를 요구하지 않습니다.","건강과 구조 경위를 사실대로 작성했습니다.","불공정한 추가 조건이나 임의 계약을 강요하지 않습니다.","허위·사기·학대·유기 시 삭제와 제재에 동의합니다."];
export function FosterRegistration(){const[educated,setEducated]=useState<boolean|null>(null),[answers,setAnswers]=useState<Record<number,boolean>>({}),[accepted,setAccepted]=useState<string[]>([]),[done,setDone]=useState(false),[error,setError]=useState(""),[mediaNames,setMediaNames]=useState("");useEffect(()=>{fetch("/api/foster-onboarding").then(r=>r.ok?r.json():{completed:false}).then(v=>setEducated(v.completed)).catch(()=>setEducated(false))},[]);const score=Math.round(questions.reduce((sum,item,index)=>sum+(answers[index]===item.a?1:0),0)/questions.length*100);
async function completeEducation(){const response=await fetch("/api/foster-onboarding",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({answers:Object.keys(answers).map(index=>answers[Number(index)])})});if(response.status===401)location.href="/login?return_to=%2Ffoster";else if(response.ok)setEducated(true);else setError("80점 이상이 필요해요. 해설을 다시 확인해 주세요.")}
async function upload(file:File){const body=new FormData();body.set("file",file.type.startsWith("image/")?await sanitizeImageFile(file):file);const response=await fetch("/api/uploads",{method:"POST",body});if(!response.ok)throw new Error((await response.json()).error);return (await response.json()).key as string}
async function register(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError("");if(accepted.length<terms.length)return setError("등록 약관을 모두 확인해 주세요.");try{const form=new FormData(event.currentTarget),photos=form.getAll("images").filter((v):v is File=>v instanceof File&&v.size).slice(0,8);if(photos.length<2)return setError("서로 다른 사진을 2장 이상 올려주세요.");const imageKeys=[] as string[];for(const photo of photos)imageKeys.push(await upload(photo));const video=form.get("video"),videoKey=video instanceof File&&video.size?await upload(video):"";const response=await fetch("/api/direct-animals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:form.get("name"),species:form.get("species"),region:form.get("region"),rescueStory:form.get("rescueStory"),adoptionTerms:form.get("adoptionTerms"),imageKeys,videoKey,health:{weight:form.get("weight"),vaccination:form.get("vaccination"),neutered:form.get("neutered"),treatment:form.get("treatment")},life:{personality:form.get("personality"),aloneTime:form.get("aloneTime"),toilet:form.get("toilet"),compatibility:form.get("compatibility")}})});if(response.status===401){location.href="/login?return_to=%2Ffoster";return}if(response.ok)setDone(true);else setError((await response.json()).error||"등록하지 못했어요.")}catch(e){setError(e instanceof Error?e.message:"파일을 올리지 못했어요.")}}
if(educated===null)return <div className="ff-empty">교육 이력을 확인하고 있어요.</div>;
if(!educated)return <section className="ff-form"><Callout tone="warning" title="개인 임시보호자 필수 교육" description="허위 정보·금전 요구·재유기 위험을 줄이는 5문항입니다. 80점 이상이면 등록할 수 있어요."/>{questions.map((item,index)=><fieldset className="ff-quiz-question" key={item.q}><legend><span>{index+1}</span>{item.q}</legend><label><input type="radio" checked={answers[index]===true} onChange={()=>setAnswers(v=>({...v,[index]:true}))}/><span>예</span></label><label><input type="radio" checked={answers[index]===false} onChange={()=>setAnswers(v=>({...v,[index]:false}))}/><span>아니오</span></label></fieldset>)}{error&&<Callout tone="critical" description={error}/>}<ActionButton size="large" disabled={Object.keys(answers).length<questions.length} onClick={completeEducation}>채점하기 · 현재 {score}점</ActionButton></section>;
if(done)return <div className="ff-result"><h2 className="ff-section-title">검토 요청을 접수했어요</h2><p className="ff-description">다중 사진·영상·건강·구조·개인정보를 운영자가 확인합니다. 공개 전까지 검토 상태로 보관돼요.</p><ActionButton asChild><a href="/mypage">등록과 신청자 관리 보기</a></ActionButton></div>;
return <form className="ff-form" onSubmit={register}><Callout tone="informative" title="개인 임시보호 등록" description="보호소 인증 마크는 제공되지 않으며 연락처와 정확한 주소는 공개하지 않습니다."/><TextField label="이름 또는 임시 이름" required><TextFieldInput name="name" required/></TextField><div className="ff-condition-grid"><div className="ff-field"><label>동물 종류<select name="species" className="ff-native-select"><option>고양이</option><option>강아지</option></select></label></div><TextField label="입양 가능 지역" description="시·구·동 수준"><TextFieldInput name="region" required/></TextField><TextField label="추정 체중"><TextFieldInput name="weight" placeholder="예: 4.2kg"/></TextField><div className="ff-field"><label>중성화<select name="neutered" className="ff-native-select"><option>미상</option><option>완료</option><option>하지 않음</option><option>예정</option></select></label></div></div><label className="ff-photo-drop ff-upload-compact"><span>서로 다른 사진 2~8장 · 각 8MB 이하</span><input name="images" type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>setMediaNames(Array.from(e.target.files||[]).map(v=>v.name).join(" · "))}/></label>{mediaNames&&<p className="ff-meta">{mediaNames}</p>}<label className="ff-photo-drop ff-upload-compact"><span>짧은 영상 1개 · MP4/WEBM, 30MB 이하</span><input name="video" type="file" accept="video/mp4,video/webm"/></label><TextField label="구조 경위와 시점" required><TextFieldTextarea name="rescueStory" minLength={30} required/></TextField><TextField label="접종·검진 기록"><TextFieldTextarea name="vaccination"/></TextField><TextField label="치료·투약·알려진 질환"><TextFieldTextarea name="treatment"/></TextField><TextField label="성격·사회성·활동량"><TextFieldTextarea name="personality"/></TextField><TextField label="혼자 있을 수 있는 시간"><TextFieldInput name="aloneTime"/></TextField><TextField label="배변·산책·생활 습관"><TextFieldTextarea name="toilet"/></TextField><TextField label="아이·다른 동물과의 관계"><TextFieldTextarea name="compatibility"/></TextField><TextField label="입양 조건과 상담할 점" required><TextFieldTextarea name="adoptionTerms" minLength={20} required/></TextField><CheckboxGroup label="등록 약관 필수 동의">{terms.map(label=><Checkbox key={label} label={label} checked={accepted.includes(label)} onCheckedChange={checked=>setAccepted(v=>checked?[...v,label]:v.filter(x=>x!==label))}/>)}</CheckboxGroup>{error&&<Callout tone="critical" description={error}/>}<ActionButton size="large">검토 요청하기</ActionButton></form>}
