"use client";
import { useMemo, useState } from "react";
import { Callout } from "seed-design/ui/callout";
import { ActionButton } from "seed-design/ui/action-button";
function band(age:number){return age<1?"성장기":age<7?"성년기":age<11?"중년기":"노년기"}
export function LifetimeCarePlanner({species,animalAge}:{species:string;animalAge:number|null}){
  const isCat=species.includes("고양이"),[petAge,setPetAge]=useState(animalAge??2),[adopterAge,setAdopterAge]=useState(35),[open,setOpen]=useState(false);
  const data=useMemo(()=>{const average=isCat?16:13,optimistic=isCat?20:16,remaining=Math.max(1,average-petAge),older=petAge>=10,annualLow=older?900000:petAge>=7?600000:350000,annualHigh=older?3000000:petAge>=7?2200000:1400000;return{average,optimistic,remaining,adopterThen:adopterAge+remaining,annualLow,annualHigh,care:isCat?["낚싯대·공놀이 10~15분씩 하루 2~3회","화장실은 고양이 수+1개, 매일 1~2회 청소","매일 식욕·음수·배변·호흡 변화 확인","주 1회 체중·피부·귀·발톱 상태 확인"]:["건강 상태에 맞춰 하루 2~3회 산책","후각 놀이·훈련 10~15분씩 하루 2회","배변·식욕·관절·호흡 변화를 매일 확인","양치 또는 구강 관리와 주 1회 전신 확인"]};},[isCat,petAge,adopterAge]);
  return <section className="ff-lifetime-card"><div className="ff-section-head"><div><div className="ff-kicker">함께할 시간을 현실적으로</div><h2 className="ff-section-title">나이와 평생 돌봄 계산</h2></div><ActionButton size="small" variant="neutralWeak" onClick={()=>setOpen(v=>!v)}>{open?"접기":"계산하기"}</ActionButton></div>{open&&<><div className="ff-age-inputs"><label>친구의 추정 나이<input type="number" min="0" max="25" value={petAge} onChange={e=>setPetAge(Number(e.target.value)||0)}/><span>살 · {band(petAge)}</span></label><label>입양자의 현재 나이<input type="number" min="18" max="90" value={adopterAge} onChange={e=>setAdopterAge(Number(e.target.value)||18)}/><span>살</span></label></div><div className="ff-lifetime-summary"><div><span>평균 수명 기준</span><strong>약 {data.remaining}년</strong><small>함께할 가능성이 있어요</small></div><div><span>그때 입양자 나이</span><strong>약 {data.adopterThen}세</strong><small>장기 돌봄 계획을 세워요</small></div><div><span>연간 진료 대비 범위</span><strong>{Math.round(data.annualLow/10000)}~{Math.round(data.annualHigh/10000)}만원</strong><small>검진·질환·응급은 별도 차이</small></div></div><Callout tone="warning" title={`${isCat?"고양이":"강아지"} 평균 수명 약 ${data.average}년 · 장수 시 ${data.optimistic}년 이상`} description="품종·체격·질환·생활환경에 따라 크게 달라지는 계획용 추정치입니다. 실제 진료비 견적이나 수명 예측이 아닙니다."/><h3>매일 사람이 해야 하는 일</h3><ul className="ff-checklist">{data.care.map(item=><li key={item}>✓ {item}</li>)}</ul></>}</section>
}
