"use client";
import { useEffect, useState } from "react";
import { ActionButton } from "seed-design/ui/action-button";
import { Badge } from "@seed-design/react";
import { Callout } from "seed-design/ui/callout";
import { TabsContent, TabsList, TabsRoot, TabsTrigger } from "seed-design/ui/tabs";
type ApplicationItem={id:number|string;animal?:string;animalId?:string;applicant?:string;status:string;score?:number;readinessScore?:number};
type RegistrationItem={id:number|string;name:string;region?:string;status:string};
type SafetyItem={id:number|string;requestedRole?:string;organization?:string;reason?:string;status?:string};
type Data={demo:boolean;notice?:string;summary:Record<string,number>;applications:ApplicationItem[];registrations:RegistrationItem[];verifications?:SafetyItem[];reports?:SafetyItem[]};
export function OperationsConsole(){const[data,setData]=useState<Data|null>(null),[error,setError]=useState("");const load=()=>fetch("/api/operations").then(r=>r.json()).then(v=>v.error?setError(v.error):setData(v));useEffect(load,[]);async function update(id:number,status:string){const response=await fetch("/api/operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"application-status",id,status,note:"운영 콘솔에서 상태 변경"})});if(!response.ok)setError((await response.json()).error);else load();}if(!data)return <div className="ff-empty">{error||"운영 데이터를 불러오고 있어요."}</div>;return <>{data.demo&&<Callout tone="warning" title="운영 콘솔 데모 모드" description={`${data.notice} 아래 사례는 기능 확인을 위한 더미 데이터이며 실제 신청자가 아닙니다.`}/>}<div className="ff-dashboard-grid ff-ops-summary"><div><strong>{data.summary.applications}</strong><span>입양 신청</span></div><div><strong>{data.summary.reviews}</strong><span>등록 심사</span></div><div><strong>{data.summary.reports}</strong><span>안전 신고</span></div><div><strong>{data.summary.returns}</strong><span>반환 도움</span></div></div><TabsRoot defaultValue="applications"><TabsList><TabsTrigger value="applications">입양 신청</TabsTrigger><TabsTrigger value="registrations">직접 등록</TabsTrigger><TabsTrigger value="safety">인증·신고</TabsTrigger></TabsList><TabsContent value="applications"><div className="ff-ops-list">{data.applications.map(item=><article key={item.id}><div><span className="ff-kicker">신청 {item.id}</span><h3>{item.animal||item.animalId}</h3><p>{item.applicant||`준비도 ${item.readinessScore}점`} · {item.status}</p></div><Badge tone="informative" variant="weak">{item.score||item.readinessScore||"-"}점</Badge>{!data.demo&&<div className="ff-ops-actions"><ActionButton size="small" variant="neutralWeak" onClick={()=>update(item.id,"consulting")}>상담</ActionButton><ActionButton size="small" onClick={()=>update(item.id,"approved")}>승인</ActionButton><ActionButton size="small" variant="criticalSolid" onClick={()=>update(item.id,"rejected")}>종료</ActionButton></div>}</article>)}</div></TabsContent><TabsContent value="registrations"><div className="ff-ops-list">{data.registrations.map(item=><article key={item.id}><div><span className="ff-kicker">등록 {item.id}</span><h3>{item.name}</h3><p>{item.region||item.status} · {item.status}</p></div><Badge tone="warning" variant="weak">검토 필요</Badge></article>)}</div></TabsContent><TabsContent value="safety"><Callout tone="informative" title="안전 우선 검토 순서" description="긴급·학대 의심 → 개인정보 노출 → 사기성 금전 요구 → 일반 운영 문의 순서로 처리합니다. 모든 조치는 감사 기록에 남습니다."/><div className="ff-ops-list">{[...(data.verifications||[]),...(data.reports||[])].map((item,index)=><article key={`${item.id}-${index}`}><div><h3>{item.requestedRole?"역할 인증 요청":"안전 신고"}</h3><p>{item.organization||item.reason||item.status}</p></div></article>)}</div></TabsContent></TabsRoot></>}
