-- 이미지 원본 미러링을 동물 테이블의 부수 효과가 아닌 재시도 가능한 작업으로 관리합니다.
create table if not exists public.animal_image_jobs (
  id bigint generated by default as identity primary key,
  animal_id text not null,
  slot integer not null check (slot in (1, 2)),
  source_url text not null,
  status text not null default 'pending' check (status in ('pending', 'processing', 'completed', 'failed')),
  attempt_count integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  storage_url text,
  last_error text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (animal_id, slot, source_url)
);

create index if not exists idx_animal_image_jobs_ready
  on public.animal_image_jobs (status, next_attempt_at, id);

alter table public.animal_image_jobs enable row level security;
revoke all on table public.animal_image_jobs from public, anon, authenticated;
