-- Supabase PostgreSQL migration generated from the existing Drizzle/D1 migrations.
-- Review and run this file in the Supabase SQL Editor before switching production reads/writes.
CREATE TABLE "applications" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"member_id" text NOT NULL,
	"animal_id" text NOT NULL,
	"status" text DEFAULT 'submitted' NOT NULL,
	"household" text NOT NULL,
	"care_plan" text NOT NULL,
	"readiness_score" integer NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL
);

CREATE TABLE "favorites" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"member_id" text NOT NULL,
	"animal_id" text NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL
);

CREATE UNIQUE INDEX "idx_favorites_member_animal" ON "favorites" ("member_id","animal_id");
CREATE TABLE "lost_reports" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"member_id" text NOT NULL,
	"kind" text NOT NULL,
	"species" text NOT NULL,
	"region" text NOT NULL,
	"occurred_at" text NOT NULL,
	"description" text NOT NULL,
	"image_key" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL
);

CREATE TABLE "members" (
	"id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"display_name" text NOT NULL,
	"role" text DEFAULT 'member' NOT NULL,
	"verified" boolean DEFAULT true NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL
);

CREATE TABLE "posts" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"member_id" text NOT NULL,
	"category" text NOT NULL,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"image_key" text,
	"hidden" boolean DEFAULT false NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL
);

CREATE TABLE "reports" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"member_id" text NOT NULL,
	"target_type" text NOT NULL,
	"target_id" text NOT NULL,
	"reason" text NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL
);

CREATE UNIQUE INDEX "idx_reports_unique_member_target" ON "reports" ("member_id","target_type","target_id");
CREATE TABLE "adoption_agreements" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"application_id" integer NOT NULL,
	"member_id" text NOT NULL,
	"version" text DEFAULT '2026-08' NOT NULL,
	"terms_json" text NOT NULL,
	"signed_name" text NOT NULL,
	"agreed_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("application_id") REFERENCES "applications"("id"),
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE UNIQUE INDEX "idx_agreements_application" ON "adoption_agreements" ("application_id");
CREATE TABLE "application_messages" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"application_id" integer NOT NULL,
	"sender_id" text NOT NULL,
	"body" text NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("application_id") REFERENCES "applications"("id"),
	FOREIGN KEY ("sender_id") REFERENCES "members"("id")
);

CREATE INDEX "idx_messages_application_created" ON "application_messages" ("application_id","created_at");
CREATE TABLE "direct_animals" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"member_id" text NOT NULL,
	"status" text DEFAULT 'review' NOT NULL,
	"name" text NOT NULL,
	"species" text NOT NULL,
	"region" text NOT NULL,
	"rescue_story" text NOT NULL,
	"health_json" text NOT NULL,
	"life_json" text NOT NULL,
	"adoption_terms" text NOT NULL,
	"image_key" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	"updated_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE INDEX "idx_direct_animals_member_status" ON "direct_animals" ("member_id","status");
CREATE TABLE "handover_reservations" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"application_id" integer NOT NULL,
	"method" text NOT NULL,
	"scheduled_at" text NOT NULL,
	"region" text NOT NULL,
	"checklist_json" text DEFAULT '[]' NOT NULL,
	"status" text DEFAULT 'proposed' NOT NULL,
	"adopter_confirmed" boolean DEFAULT false NOT NULL,
	"guardian_confirmed" boolean DEFAULT false NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("application_id") REFERENCES "applications"("id")
);

CREATE UNIQUE INDEX "idx_handover_application" ON "handover_reservations" ("application_id");
CREATE TABLE "post_reactions" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"member_id" text NOT NULL,
	"post_id" integer NOT NULL,
	"reaction" text DEFAULT 'cheer' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id"),
	FOREIGN KEY ("post_id") REFERENCES "posts"("id")
);

CREATE UNIQUE INDEX "idx_post_reactions_member_post" ON "post_reactions" ("member_id","post_id");
CREATE TABLE "readiness_assessments" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"member_id" text NOT NULL,
	"species" text NOT NULL,
	"profile_json" text NOT NULL,
	"readiness_score" integer NOT NULL,
	"education_score" integer NOT NULL,
	"passed" boolean DEFAULT false NOT NULL,
	"completed_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE INDEX "idx_readiness_member_completed" ON "readiness_assessments" ("member_id","completed_at");
ALTER TABLE "applications" ADD "readiness_assessment_id" integer;
ALTER TABLE "applications" ADD "absence_plan" text DEFAULT '' NOT NULL;
ALTER TABLE "applications" ADD "emergency_plan" text DEFAULT '' NOT NULL;
ALTER TABLE "applications" ADD "agreement_accepted" boolean DEFAULT false NOT NULL;
CREATE INDEX "idx_applications_member_status" ON "applications" ("member_id","status");
ALTER TABLE "lost_reports" ADD "ownership_question" text DEFAULT '' NOT NULL;
ALTER TABLE "lost_reports" ADD "alert_region" text DEFAULT '' NOT NULL;
ALTER TABLE "members" ADD "sanctioned" boolean DEFAULT false NOT NULL;
ALTER TABLE "members" ADD "foster_education_completed" boolean DEFAULT false NOT NULL;

CREATE TABLE "application_events" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"application_id" integer NOT NULL,
	"actor_id" text NOT NULL,
	"event_type" text NOT NULL,
	"note" text DEFAULT '' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("application_id") REFERENCES "applications"("id"),
	FOREIGN KEY ("actor_id") REFERENCES "members"("id")
);

CREATE INDEX "idx_application_events_application_created" ON "application_events" ("application_id","created_at");
CREATE TABLE "moderation_actions" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"actor_id" text NOT NULL,
	"target_type" text NOT NULL,
	"target_id" text NOT NULL,
	"action" text NOT NULL,
	"reason" text NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("actor_id") REFERENCES "members"("id")
);

CREATE INDEX "idx_moderation_target_created" ON "moderation_actions" ("target_type","target_id","created_at");
CREATE TABLE "notifications" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"member_id" text NOT NULL,
	"type" text NOT NULL,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"href" text DEFAULT '/mypage' NOT NULL,
	"read" boolean DEFAULT false NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE INDEX "idx_notifications_member_read_created" ON "notifications" ("member_id","read","created_at");
CREATE TABLE "return_requests" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"application_id" integer NOT NULL,
	"member_id" text NOT NULL,
	"urgency" text NOT NULL,
	"reason" text NOT NULL,
	"safe_until" text DEFAULT '' NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("application_id") REFERENCES "applications"("id"),
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE INDEX "idx_return_requests_status_created" ON "return_requests" ("status","created_at");
CREATE TABLE "saved_searches" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"member_id" text NOT NULL,
	"name" text NOT NULL,
	"criteria_json" text NOT NULL,
	"alerts_enabled" boolean DEFAULT true NOT NULL,
	"last_matched_at" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE INDEX "idx_saved_searches_member_created" ON "saved_searches" ("member_id","created_at");
CREATE TABLE "verification_requests" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"member_id" text NOT NULL,
	"requested_role" text NOT NULL,
	"organization" text DEFAULT '' NOT NULL,
	"evidence_key" text,
	"status" text DEFAULT 'submitted' NOT NULL,
	"reviewed_by" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE INDEX "idx_verification_status_created" ON "verification_requests" ("status","created_at");
ALTER TABLE "reports" ADD "severity" text DEFAULT 'normal' NOT NULL;

CREATE TABLE "account_sanctions" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"member_id" text NOT NULL,
	"actor_id" text NOT NULL,
	"reason" text NOT NULL,
	"status" text DEFAULT 'proposed' NOT NULL,
	"fingerprint_hash" text DEFAULT '' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id"),
	FOREIGN KEY ("actor_id") REFERENCES "members"("id")
);

CREATE INDEX "idx_account_sanctions_member_status" ON "account_sanctions" ("member_id","status");
CREATE TABLE "admin_audit_logs" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"actor_id" text NOT NULL,
	"action" text NOT NULL,
	"target_type" text NOT NULL,
	"target_id" text NOT NULL,
	"before_json" text DEFAULT '{}' NOT NULL,
	"after_json" text DEFAULT '{}' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("actor_id") REFERENCES "members"("id")
);

CREATE INDEX "idx_admin_audit_target_created" ON "admin_audit_logs" ("target_type","target_id","created_at");
CREATE TABLE "animal_media" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"animal_id" integer NOT NULL,
	"media_type" text NOT NULL,
	"object_key" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("animal_id") REFERENCES "direct_animals"("id")
);

CREATE INDEX "idx_animal_media_animal_order" ON "animal_media" ("animal_id","sort_order");
CREATE TABLE "family_opinions" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"room_id" integer NOT NULL,
	"author_name" text NOT NULL,
	"decision" text NOT NULL,
	"body" text NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL
);

CREATE INDEX "idx_family_opinions_room_created" ON "family_opinions" ("room_id","created_at");
CREATE TABLE "family_rooms" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"owner_id" text NOT NULL,
	"animal_id" text NOT NULL,
	"share_token" text NOT NULL,
	"title" text NOT NULL,
	"status" text DEFAULT 'discussing' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("owner_id") REFERENCES "members"("id")
);

CREATE UNIQUE INDEX "idx_family_rooms_token" ON "family_rooms" ("share_token");
CREATE INDEX "idx_family_rooms_owner" ON "family_rooms" ("owner_id");
CREATE TABLE "lost_matches" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"lost_report_id" integer NOT NULL,
	"found_report_id" integer NOT NULL,
	"score" integer NOT NULL,
	"reasons_json" text NOT NULL,
	"status" text DEFAULT 'suggested' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("lost_report_id") REFERENCES "lost_reports"("id"),
	FOREIGN KEY ("found_report_id") REFERENCES "lost_reports"("id")
);

CREATE UNIQUE INDEX "idx_lost_matches_pair" ON "lost_matches" ("lost_report_id","found_report_id");
CREATE TABLE "lost_messages" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"report_id" integer NOT NULL,
	"sender_id" text NOT NULL,
	"body" text NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("report_id") REFERENCES "lost_reports"("id"),
	FOREIGN KEY ("sender_id") REFERENCES "members"("id")
);

CREATE INDEX "idx_lost_messages_report_created" ON "lost_messages" ("report_id","created_at");
CREATE TABLE "lost_timeline_events" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"report_id" integer NOT NULL,
	"member_id" text NOT NULL,
	"region" text NOT NULL,
	"occurred_at" text NOT NULL,
	"note" text NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("report_id") REFERENCES "lost_reports"("id"),
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE INDEX "idx_lost_timeline_report_occurred" ON "lost_timeline_events" ("report_id","occurred_at");
CREATE TABLE "shelter_needs" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"shelter_id" integer NOT NULL,
	"item_name" text NOT NULL,
	"target_quantity" integer NOT NULL,
	"received_quantity" integer DEFAULT 0 NOT NULL,
	"unit_price" integer DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'needed' NOT NULL
);

CREATE INDEX "idx_shelter_needs_shelter_status" ON "shelter_needs" ("shelter_id","status");
CREATE TABLE "shelter_profiles" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"owner_id" text,
	"public_id" text NOT NULL,
	"name" text NOT NULL,
	"organization" text DEFAULT '' NOT NULL,
	"region" text NOT NULL,
	"introduction" text NOT NULL,
	"verified" boolean DEFAULT false NOT NULL,
	"image_key" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("owner_id") REFERENCES "members"("id")
);

CREATE UNIQUE INDEX "idx_shelter_profiles_public_id" ON "shelter_profiles" ("public_id");
CREATE INDEX "idx_shelter_profiles_region" ON "shelter_profiles" ("region");
CREATE TABLE "shelter_updates" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"shelter_id" integer NOT NULL,
	"author_id" text,
	"category" text DEFAULT 'daily' NOT NULL,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"image_key" text,
	"hidden" boolean DEFAULT false NOT NULL,
	"reactions" integer DEFAULT 0 NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("shelter_id") REFERENCES "shelter_profiles"("id"),
	FOREIGN KEY ("author_id") REFERENCES "members"("id")
);

CREATE INDEX "idx_shelter_updates_shelter_created" ON "shelter_updates" ("shelter_id","created_at");
CREATE TABLE "support_records" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"member_id" text NOT NULL,
	"kind" text NOT NULL,
	"target_id" text DEFAULT '' NOT NULL,
	"title" text NOT NULL,
	"amount" integer DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'intent' NOT NULL,
	"disclosure" text DEFAULT '' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE INDEX "idx_support_records_member_created" ON "support_records" ("member_id","created_at");
CREATE TABLE "volunteer_applications" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"post_id" integer NOT NULL,
	"member_id" text NOT NULL,
	"message" text DEFAULT '' NOT NULL,
	"status" text DEFAULT 'submitted' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE UNIQUE INDEX "idx_volunteer_application_unique" ON "volunteer_applications" ("post_id","member_id");
CREATE TABLE "volunteer_posts" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"shelter_id" integer NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"region" text NOT NULL,
	"scheduled_at" text NOT NULL,
	"capacity" integer DEFAULT 1 NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("shelter_id") REFERENCES "shelter_profiles"("id")
);

CREATE INDEX "idx_volunteer_posts_shelter_status" ON "volunteer_posts" ("shelter_id","status");
ALTER TABLE "applications" ADD "suitability_score" integer DEFAULT 0 NOT NULL;
ALTER TABLE "applications" ADD "suitability_json" text DEFAULT '{}' NOT NULL;
ALTER TABLE "lost_reports" ADD "status" text DEFAULT 'active' NOT NULL;
ALTER TABLE "lost_reports" ADD "visual_tags_json" text DEFAULT '[]' NOT NULL;
ALTER TABLE "members" ADD "home_region" text DEFAULT '' NOT NULL;
ALTER TABLE "posts" ADD "views" integer DEFAULT 0 NOT NULL;
ALTER TABLE "posts" ADD "shares" integer DEFAULT 0 NOT NULL;
ALTER TABLE "posts" ADD "updated_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL;

ALTER TABLE "applications" ADD "guardian_id" text REFERENCES members(id);
ALTER TABLE "verification_requests" ADD "representative_name" text DEFAULT '' NOT NULL;
ALTER TABLE "verification_requests" ADD "business_number" text DEFAULT '' NOT NULL;
ALTER TABLE "verification_requests" ADD "shelter_type" text DEFAULT '' NOT NULL;
CREATE TABLE "adoption_certifications" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"member_id" text NOT NULL,
	"application_id" integer,
	"source" text NOT NULL,
	"shelter_name" text DEFAULT '' NOT NULL,
	"animal_name" text DEFAULT '' NOT NULL,
	"verification_code_hash" text DEFAULT '' NOT NULL,
	"evidence_key" text,
	"status" text DEFAULT 'submitted' NOT NULL,
	"reviewed_by" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id"),
	FOREIGN KEY ("application_id") REFERENCES "applications"("id")
);

CREATE INDEX "idx_adoption_certifications_member_status" ON "adoption_certifications" ("member_id","status");
CREATE TABLE "sanction_appeals" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"sanction_id" integer NOT NULL,
	"member_id" text NOT NULL,
	"reason" text NOT NULL,
	"evidence_key" text,
	"status" text DEFAULT 'submitted' NOT NULL,
	"reviewed_by" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("sanction_id") REFERENCES "account_sanctions"("id"),
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE INDEX "idx_sanction_appeals_status_created" ON "sanction_appeals" ("status","created_at");
CREATE TABLE "shelter_update_reactions" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"update_id" integer NOT NULL,
	"member_id" text NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("update_id") REFERENCES "shelter_updates"("id"),
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE UNIQUE INDEX "idx_shelter_update_reaction_unique" ON "shelter_update_reactions" ("update_id","member_id");
ALTER TABLE "direct_animals" ADD "reconfirmed_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL;
CREATE TABLE "auth_accounts" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"member_id" text NOT NULL,
	"provider" text NOT NULL,
	"provider_user_id" text NOT NULL,
	"email" text NOT NULL,
	"password_hash" text,
	"password_salt" text,
	"email_verified" boolean DEFAULT false NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE UNIQUE INDEX "idx_auth_accounts_provider_user" ON "auth_accounts" ("provider","provider_user_id");
CREATE INDEX "idx_auth_accounts_email" ON "auth_accounts" ("email");
CREATE TABLE "auth_sessions" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"member_id" text NOT NULL,
	"token_hash" text NOT NULL,
	"expires_at" text NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE UNIQUE INDEX "idx_auth_sessions_token" ON "auth_sessions" ("token_hash");
CREATE INDEX "idx_auth_sessions_member_expires" ON "auth_sessions" ("member_id","expires_at");
ALTER TABLE "applications" ADD "shelter_public_id" text;
CREATE TABLE "animal_name_suggestions" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"animal_id" text NOT NULL,
	"member_id" text NOT NULL,
	"name" text NOT NULL,
	"reason" text DEFAULT '' NOT NULL,
	"votes" integer DEFAULT 0 NOT NULL,
	"selected" boolean DEFAULT false NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE UNIQUE INDEX "idx_animal_name_member_name" ON "animal_name_suggestions" ("animal_id","member_id","name");
CREATE INDEX "idx_animal_name_votes" ON "animal_name_suggestions" ("animal_id","votes");
CREATE TABLE "animal_name_votes" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"suggestion_id" integer NOT NULL,
	"member_id" text NOT NULL,
	FOREIGN KEY ("suggestion_id") REFERENCES "animal_name_suggestions"("id"),
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE UNIQUE INDEX "idx_animal_name_vote_unique" ON "animal_name_votes" ("suggestion_id","member_id");
CREATE TABLE "community_answers" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"question_id" integer NOT NULL,
	"member_id" text NOT NULL,
	"body" text NOT NULL,
	"helpful" integer DEFAULT 0 NOT NULL,
	"accepted" boolean DEFAULT false NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE INDEX "idx_community_answers_question_helpful" ON "community_answers" ("question_id","helpful");
CREATE TABLE "community_questions" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"member_id" text NOT NULL,
	"category" text NOT NULL,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE INDEX "idx_community_questions_status_created" ON "community_questions" ("status","created_at");
CREATE TABLE "drawing_matches" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"post_id" integer NOT NULL,
	"member_id" text NOT NULL,
	"animal_id" text NOT NULL,
	"reason" text NOT NULL,
	"selected" boolean DEFAULT false NOT NULL,
	"points" integer DEFAULT 0 NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE UNIQUE INDEX "idx_drawing_match_unique" ON "drawing_matches" ("post_id","member_id","animal_id");
CREATE TABLE "drawing_posts" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"member_id" text NOT NULL,
	"image_key" text NOT NULL,
	"species" text NOT NULL,
	"title" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"tags_json" text DEFAULT '[]' NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE INDEX "idx_drawing_posts_status_created" ON "drawing_posts" ("status","created_at");
CREATE TABLE "fundraiser_pledges" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"fundraiser_id" integer NOT NULL,
	"member_id" text NOT NULL,
	"amount" integer NOT NULL,
	"status" text DEFAULT 'pledged' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);


CREATE INDEX "idx_fundraiser_pledges_campaign" ON "fundraiser_pledges" ("fundraiser_id","created_at");
CREATE TABLE "fundraisers" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"shelter_id" integer NOT NULL,
	"animal_id" text NOT NULL,
	"title" text NOT NULL,
	"purpose" text NOT NULL,
	"target_amount" integer NOT NULL,
	"raised_amount" integer DEFAULT 0 NOT NULL,
	"evidence_key" text,
	"status" text DEFAULT 'review' NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("shelter_id") REFERENCES "shelter_profiles"("id")
);

CREATE INDEX "idx_fundraisers_status_created" ON "fundraisers" ("status","created_at");
CREATE TABLE "volunteer_badges" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"member_id" text NOT NULL,
	"kind" text NOT NULL,
	"label" text NOT NULL,
	"awarded_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE UNIQUE INDEX "idx_volunteer_badge_unique" ON "volunteer_badges" ("member_id","kind");
ALTER TABLE "applications" ADD "adopter_age" integer DEFAULT 0 NOT NULL;
ALTER TABLE "volunteer_posts" ADD "category" text DEFAULT 'care' NOT NULL;
CREATE TABLE "public_animals" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"species" text NOT NULL,
	"breed" text NOT NULL,
	"age" text NOT NULL,
	"age_group" text NOT NULL,
	"sex" text NOT NULL,
	"region" text NOT NULL,
	"shelter_id" text,
	"shelter_name" text NOT NULL,
	"shelter_address" text DEFAULT '' NOT NULL,
	"shelter_phone" text DEFAULT '' NOT NULL,
	"shelter_lat" real,
	"shelter_lng" real,
	"approximate_shelter_location" boolean DEFAULT false NOT NULL,
	"updated" text NOT NULL,
	"image_1" text NOT NULL,
	"image_2" text DEFAULT '' NOT NULL,
	"colors_json" text DEFAULT '[]' NOT NULL,
	"traits_json" text DEFAULT '[]' NOT NULL,
	"summary" text NOT NULL,
	"health_json" text DEFAULT '[]' NOT NULL,
	"life_json" text DEFAULT '[]' NOT NULL,
	"match_reason" text NOT NULL,
	"process_state" text DEFAULT '' NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"last_seen_sync" text NOT NULL,
	"synced_at" text NOT NULL
);

CREATE INDEX "idx_public_animals_active_updated" ON "public_animals" ("active","updated");
CREATE INDEX "idx_public_animals_species_active" ON "public_animals" ("species","active");
CREATE INDEX "idx_public_animals_shelter" ON "public_animals" ("shelter_id");
CREATE TABLE "public_shelters" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"organization" text DEFAULT '' NOT NULL,
	"address" text DEFAULT '' NOT NULL,
	"phone" text DEFAULT '' NOT NULL,
	"hours" text DEFAULT '' NOT NULL,
	"closed" text DEFAULT '' NOT NULL,
	"lat" real,
	"lng" real,
	"approximate_location" boolean DEFAULT false NOT NULL,
	"synced_at" text NOT NULL
);

CREATE INDEX "idx_public_shelters_name" ON "public_shelters" ("name");
CREATE TABLE "public_sync_state" (
	"id" text PRIMARY KEY NOT NULL,
	"status" text NOT NULL,
	"last_started_at" text NOT NULL,
	"last_completed_at" text,
	"item_count" integer DEFAULT 0 NOT NULL,
	"page_count" integer DEFAULT 0 NOT NULL,
	"message" text DEFAULT '' NOT NULL
);

ALTER TABLE "public_animals" ADD "up_kind_cd" text DEFAULT '' NOT NULL;
ALTER TABLE "public_animals" ADD "kind_cd" text DEFAULT '' NOT NULL;
CREATE INDEX "idx_public_animals_kind_active" ON "public_animals" ("up_kind_cd","kind_cd","active");
CREATE TABLE "shelter_follows" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"shelter_public_id" text NOT NULL,
	"member_id" text NOT NULL,
	"created_at" text DEFAULT CURRENT_TIMESTAMP::text NOT NULL,
	FOREIGN KEY ("member_id") REFERENCES "members"("id")
);

CREATE UNIQUE INDEX "idx_shelter_follow_unique" ON "shelter_follows" ("shelter_public_id","member_id");
CREATE INDEX "idx_shelter_follow_member" ON "shelter_follows" ("member_id");

-- Deferred foreign keys: these tables are created before their referenced tables.
ALTER TABLE "applications" ADD FOREIGN KEY ("member_id") REFERENCES "members"("id");
ALTER TABLE "favorites" ADD FOREIGN KEY ("member_id") REFERENCES "members"("id");
ALTER TABLE "lost_reports" ADD FOREIGN KEY ("member_id") REFERENCES "members"("id");
ALTER TABLE "posts" ADD FOREIGN KEY ("member_id") REFERENCES "members"("id");
ALTER TABLE "reports" ADD FOREIGN KEY ("member_id") REFERENCES "members"("id");
ALTER TABLE "family_opinions" ADD FOREIGN KEY ("room_id") REFERENCES "family_rooms"("id");
ALTER TABLE "shelter_needs" ADD FOREIGN KEY ("shelter_id") REFERENCES "shelter_profiles"("id");
ALTER TABLE "volunteer_applications" ADD FOREIGN KEY ("post_id") REFERENCES "volunteer_posts"("id");
ALTER TABLE "community_answers" ADD FOREIGN KEY ("question_id") REFERENCES "community_questions"("id");
ALTER TABLE "drawing_matches" ADD FOREIGN KEY ("post_id") REFERENCES "drawing_posts"("id");
ALTER TABLE "fundraiser_pledges" ADD FOREIGN KEY ("fundraiser_id") REFERENCES "fundraisers"("id");
